version: "3.8"

services:
  tsoha-server-dev:
    build: .
    depends_on:
      - postgres
    command: poetry run python3 -m flask run --host=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
