version: "3.8"

services:
  client:
    build: client
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build: server
    depends_on:
      - postgres
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
